name: C/C++ CI

on: [push]

jobs:
  ubuntu-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'taiwins-ubuntu'
    - name: submodule
      run: git submodule update --init --recursive
      working-directory: './taiwins-ubuntu'
    - name: install dependencies for ubuntu
      run: |
        chmod +x ./.github/actions/ubuntu-deps.sh
        .github/actions/ubuntu-deps.sh
      working-directory: './taiwins-ubuntu'
    - name: clean build
      working-directory: './taiwins-ubuntu'
      run: rm -rf build && mkdir -p build
    - name: build
      working-directory: './taiwins-ubuntu/'
      run: |
        export PATH=~/.local/bin:$PATH
        export PKG_CONFIG_PATH=/usr/local/lib:${PKG_CONFIG_PATH}
        meson build && ninja -C build
        # cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ .. && make
        
  other-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: git submodule update --init --recursive
    - name: run with archlinux docker img
      uses: docker://archlinux/base:latest
      with:
        entrypoint: ./.github/actions/entrypoint.sh
